name: Deploy to production

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-deploy:
    uses: ./.github/workflows/test-and-deploy.yaml
    with:
      environment-id: 8adb909a-c5d9-4756-9920-cdc7ddb776bd
      application-id: 0b145e1e-8c76-4872-a75c-74b216f4dac
