name: Deploy to staging
on:
  push:
    branches:
      - develop
jobs:
  test-and-deploy:
    uses: ./.github/workflows/test-and-deploy.yaml
    with:
      organization-id: 4f87eada-1799-4beb-a281-9610400586c0 
      environment-id: 4d13cd36-6134-41db-b27f-709f63340add
      application-id: f22890e1-7b53-4c69-b0ab-a0ee47eeb141
    secrets:
      api-token: ${{ secrets.QOVERY_API_TOKEN }}        
