name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  test-and-deploy:
    uses: ./.github/workflows/test-and-deploy.yaml
    with:
      organization-id: 4f87eada-1799-4beb-a281-9610400586c0 
      environment-id: 8adb909a-c5d9-4756-9920-cdc7ddb776bd
      application-ids: 0b145e1e-8c76-4872-a75c-74b216f4dac0
    secrets:
      api-token: ${{ secrets.QOVERY_API_TOKEN }}        
