name: Test And Deploy to Qovery
on:
  workflow_call:
    inputs:
      organization-id:
        required: true
        type: string     
      environment-id:
        required: true
        type: string 
      application-ids:
        required: true
        type: string                        
    secrets:
      api-token:
        required: true
jobs:
  add-run-id-to-env-name:
    # needs: deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_ID: ${{ inputs.environment-id }}
      QOVERY_API_TOKEN: ${{ secrets.api-token }}
    steps:
      - uses: actions/checkout@v2
      - name: Add Workflow execution ID to env name
        run: ./.github/scripts/add-run-id-to-env-name.sh
        shell: bash
