name: Test And Deploy to Qovery
on:
  workflow_call:
    inputs:
      environment-id:
        required: true
        type: string 
      application-id:
        required: true
        type: string                        
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy on Qovery
        uses: Qovery/qovery-action@main
        id: qovery
        with:
          qovery-organization-id: 4f87eada-1799-4beb-a281-9610400586c0 
          qovery-environment-id: ${{ inputs.environment-id }}
          qovery-application-id: ${{ inputs.application-id }}
          qovery-api-token: ${{ secrets.QOVERY_API_TOKEN }}
