name: Test And Deploy to Qovery
on:
  workflow_call:
    inputs:
      organization-id:
        required: true
        type: string     
      environment-id:
        required: true
        type: string 
      application-ids:
        required: true
        type: string                        
    secrets:
      api-token:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on Qovery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy on Qovery
        uses: l0ck3/qovery-github-actions@main
        id: qovery
        with:
          qovery-organization-id: ${{ inputs.organization-id }} 
          qovery-environment-id: ${{ inputs.environment-id }}
          qovery-application-ids: ${{ inputs.application-ids }}
          qovery-api-token: ${{ secrets.api-token }}
