name: Test And Deploy to Qovery
on:
  workflow_call:
    inputs:
      organization-id:
        required: true
        type: string     
      environment-id:
        required: true
        type: string 
      application-ids:
        required: true
        type: string                        
    secrets:
      api-token:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
